aboutcode-org/vulnerablecode

requirements.txt
=> Update Django version

README.md, vulnerablecode/dev.py
- Fix instructions for Debian-based distros
- Add instructions for running Postgres in Docker
- Set DJANGO_DEV=1 in runserver call to have localhost in ALLOWED_HOSTS
closes #47
=> Improve setup instructions in README

README.md
=> Document methods for periodic data  import

vulnerabilities/scraper/npm.py
=> Add missing variable name.

README.md
Signed-off-by: sbs2001 <shivam.sandbhor@gmail.com>
=> Update README instructions for running tests

vulnerabilities/models.py
Signed-off-by: sbs2001 <shivam.sandbhor@gmail.com>
Fixes [this issue](https://github.com/nexB/vulnerablecode/issues/136)
=> Fixes typo in Django admin

vulnerabilities/scraper/rust.py, vulnerabilities/tests/test_rust.py
Signed-off-by: Islam ElHakmi <eslam.elhakmey3@gmail.com>
This test is to quickly detect issues like https://github.com/nexB/vulnerablecode/issues/154 for rust scraper.
/cc @sbs2001 @haikoschol @pombredanne
=> Test: add tests for rust scraper

vulnerabilities/data_dump.py, vulnerabilities/management/commands/import.py, vulnerabilities/scraper/ruby.py, vulnerabilities/scraper/safety_db.py
This is all my fault. 
During testing, I guess I was just checking whether the data gathering process was working properly. The data dump process was actually not working properly(rather not even starting). 
This PR aims to make safetydb importer work  as expected.
=> Fix safetydb

vulnerabilities/data_dump.py, vulnerabilities/management/commands/import.py, vulnerabilities/scraper/alpine_linux.py
Fixes https://github.com/nexB/vulnerablecode/issues/43
I'm not sure what 'type' to assign to these packages (apk?)
=> Add alpine linux importer

requirements.txt, vulnerabilities/scraper/safety_db.py
This is to keep track of schema changes in the advisory. 
Eventually we will add such validators for every importer
=> Add schema validation for safety_db importer

vulnerabilities/scraper/alpine_linux.py
Continuation of implementation schema  validators.
=> Add schema validator for Alpine linux

requirements.txt
These got added when I was trying to add progress bars to importers.
=> Remove unrequired dependencies

vulnerabilities/importers/alpine_linux.py
=> Update the schema validator in  alpine linux importer

vulnerabilities/management/commands/import.py
=> Add type conversion to int for batch_size , when batch_size is specified via cli

vulnerabilities/importers/gentoo.py, vulnerabilities/migrations/0014_gentoo_importer.py, vulnerabilities/tests/test_data/gentoo/glsa-201709-09.xml, vulnerabilities/tests/test_gentoo.py
Fixes https://github.com/nexB/vulnerablecode/issues/69
=> Add Gentoo Linux Security Advisory importer and it's tests

docs/how-to-guides/add_new_importer.rst
A start to adding documentation
=> Add docs directory and add tutorial about adding new importer

vulnerabilities/importers/github.py, vulnerabilities/importers/npm.py
These probably remained due to the whole rebase thing and print statements slipped through
=> Remove print statements

docs/how-to-guides/add_new_importer.rst
Things have changed. The docs now show the new procedure to register an importer
=>  Update docs for importer_yielder.py

vulnerabilities/importers/debian.py
=> :bug: Fix bug in debian's response_is_new method

README.md
=> Use New README

vulnerabilities/forms.py, vulnerabilities/templates/vulnerabilities.html, vulnerabilities/views.py
=>  Fix UI bug with vulnerability search view's pagination

README.md
=>  Add links in README.md

README.rst
I have fixed the spelling mistakes and grammatical errors ( issue #268  )  in README.rst
=> Fixed the spelling mistakes and grammatical errors

requirements.txt, vulnerabilities/import_runner.py, vulnerabilities/importer_yielder.py, vulnerabilities/importers/__init__.py, vulnerabilities/importers/github.py, vulnerabilities/importers/nginx.py, vulnerabilities/importers/postgresql.py, vulnerabilities/models.py, vulnerabilities/package_managers.py
This is based off https://github.com/nexB/vulnerablecode/pull/264
Fixes https://github.com/nexB/vulnerablecode/issues/98
=> Add postgresql importer

vulnerabilities/templates/packages.html, vulnerabilities/views.py
Fix https://github.com/nexB/vulnerablecode/issues/325
=> Fix package result count in  web ui

vulnerabilities/templates/vulnerabilities.html
=> Add message when no vulnerabilities are found for a vuln_id

vulnerabilities/tests/test_api.py, vulnerablecode/urls.py
=> Make trailing slash optional in apis

vulnerabilities/importers/alpine_linux.py
=> Disable schema validation for alpine linux to fix nix test

vulnerabilities/views.py
Fixes https://github.com/nexB/vulnerablecode/issues/359
=> Use case insensitive inexact lookups for search views

vulnerabilities/severity_systems.py, vulnerabilities/tests/test_github.py
=> Use a more specific url for cvss qualitative severity system.

vulnerabilities/importers/debian.py, vulnerabilities/importers/project_kb_msr2019.py, vulnerabilities/tests/test_data/kbmsr2019/test_msr_data.csv, vulnerabilities/tests/test_msr2019.py, vulnerabilities/tests/test_nginx.py
- Update debian importer's schema validation
- Add tests for msr2019 importer.
=> Fix various importer errors

AUTHORS.rst
I hope no review is required :p
=> Add me to AUTHORS

etc/nix/flake.nix, requirements.txt
This is the ideal scenario: Simply run ``get-latest-pypi-deps-db.sh``, copy&paste, run, commit.
=> Update nix deps.

vulnerabilities/importers/__init__.py
Signed-off-by: 司芳源 <sify1221@gmail.com>
=> remove duplicate import in importers

vulnerabilities/helpers.py
Provide a helper for uniform cve search in importers.
Based on https://github.com/nexB/vulnerablecode/pull/393#discussion_r609752301
=> expose find_all_cve helper

vulnerabilities/severity_systems.py
Fixes: https://github.com/nexB/vulnerablecode/issues/550
Signed-off-by: keshav-space <keshav6240@gmail.com>
=> Correct notes for cvssv3.1_qr

vulnerabilities/improve_runner.py, vulnerabilities/improver.py
=> Make sure fixed purl is optional in Inference

vulnerabilities/api.py
=> Fix API crash due to model changes

vulnerabilities/importers/debian.py
=> Update debian NOTICE

vulnerabilities/importers/nvd.py, vulnerabilities/migrations/0016_update_cpe_url.py, vulnerabilities/tests/test_data/nvd/nvd-expected.json, vulnerabilities/tests/test_data_migrations.py
=> Add URLs to CPEs

CHANGELOG.rst, docs/source/misc.rst
This PR is to prepare the penultimate release candidate.
=> Prepare Release 30.0.0rc2

CHANGELOG.rst, vulnerabilities/api.py, vulnerabilities/pagination.py, vulnerabilities/tests/test_fix_api.py, vulnerablecode/settings.py
=> Paginate initial listings to display a small number of or records

CHANGELOG.rst, vulnerabilities/api.py, vulnerabilities/tests/test_fix_api.py
=> Add bulk search support for CPEs #808

CHANGELOG.rst, vulnerabilities/api.py, vulnerabilities/tests/test_fix_api.py
=> Fix typos in API

CHANGELOG.rst, vulnerabilities/api.py, vulnerabilities/models.py, vulnerabilities/tests/test_fix_api.py
Reference: https://github.com/nexB/vulnerablecode/issues/867
=> Add is_vulnerable property in fixed and affected_packages

vulnerabilities/tests/test_forms.py, vulnerabilities/views.py
=> Allow case insensitive search for VCIDs #875

vulnerabilities/templates/vulnerability_details.html, vulnerablecode/static/css/custom.css
Reference: https://github.com/nexB/vulnerablecode/issues/916
Signed-off-by: John M. Horan <johnmhoran@gmail.com>
=> Fix UI wrap issue in Reference table #916

requirements.txt, vulnerabilities/models.py, vulnerabilities/views.py
Reference: https://github.com/nexB/vulnerablecode/issues/918
=> Bump package-url version #918

CHANGELOG.rst, vulnerabilities/api.py, vulnerabilities/models.py, vulnerabilities/tests/test_fix_api.py, vulnerabilities/tests/test_fix_models.py
Reference: https://github.com/nexB/vulnerablecode/issues/929
=> Add API endpoint to get all vulnerable packages #929

CHANGELOG.rst, setup.cfg, vulnerablecode/__init__.py
=> Prepare for v30.1.0

CHANGELOG.rst, setup.cfg, vulnerabilities/package_managers.py, vulnerablecode/__init__.py
=> Do additional checks in LaunchPadVersionAPI #975

CHANGELOG.rst, vulnerabilities/templates/vulnerability_details.html
Reference: https://github.com/nexB/vulnerablecode/issues/982
=> Fix severity table column spillover

.github/workflows/pypi-release.yml, CHANGELOG.rst, setup.cfg, vulnerablecode/__init__.py
=> Prepare for release v31.1.0

setup.cfg, vulnerablecode/__init__.py
=> Prepare for release v31.1.1

CHANGELOG.rst, vulnerabilities/importers/__init__.py, vulnerabilities/importers/gentoo.py, vulnerabilities/tests/conftest.py, vulnerabilities/tests/test_data/gentoo/gentoo-expected.json, vulnerabilities/tests/test_gentoo.py
=> Migrate gentoo importer #1055

CHANGELOG.rst, vulnerabilities/importers/__init__.py, vulnerabilities/importers/istio.py, vulnerabilities/improvers/default.py, vulnerabilities/tests/conftest.py, vulnerabilities/tests/test_data/istio/istio-expected.json, vulnerabilities/tests/test_data/istio/test_file.md, vulnerabilities/tests/test_istio.py
=> Migrate istio importer #1059

CHANGELOG.rst, vulnerabilities/importers/__init__.py, vulnerabilities/importers/suse_scores.py, vulnerabilities/tests/conftest.py, vulnerabilities/tests/test_data/suse_scores/suse-cvss-scores-expected.json, vulnerabilities/tests/test_suse_scores.py
=> Migrate suse scoring importer #1052

CHANGELOG.rst, setup.cfg, vulnerablecode/__init__.py
=> Prepare for release v32.0.0rc1

CHANGELOG.rst, setup.cfg, vulnerablecode/__init__.py
=> Prepare for release v32.0.0rc2

vulnerabilities/importers/istio.py, vulnerabilities/improvers/__init__.py, vulnerabilities/tests/test_data/istio/istio-improver-expected.json, vulnerabilities/tests/test_istio.py
=> Add istio improver

vulnerabilities/importers/__init__.py, vulnerabilities/importers/ubuntu.py, vulnerabilities/importers/ubuntu_usn.py, vulnerabilities/tests/conftest.py, vulnerabilities/tests/test_data/ubuntu_usn_db/ubuntu-usn-expected.json, vulnerabilities/tests/test_ubuntu_usn.py
=> Migrate ubuntu usn importer #1051

CHANGELOG.rst, setup.cfg, vulnerablecode/__init__.py
=> Prepare for release v32.0.0rc3

vulntotal/datasources/github.py, vulntotal/vulntotal_utils.py
- DataSource must load env variable before accessing it
- Skip empty version constraints in GitLab advisory
Signed-off-by: Keshav Priyadarshi <git@keshav.space>
=> minor fix: load env for GitHub DataSource

vulnerabilities/templates/vulnerability_details.html, vulnerablecode/static/css/custom.css
Reference: https://github.com/nexB/vulnerablecode/issues/1279
=> Fix Vulnerability details text overflow

vulnerabilities/templates/vulnerability_details.html, vulnerabilities/utils.py, vulnerabilities/views.py
=> Add support for severity range

vulnerabilities/templates/package_details.html
@johnmhoran fixed it! thanks for reporting the issue
=> Fix issue 1385

vulnerabilities/importers/github.py
Fixes: #656 
Changes:
- Added the license_url
=> Add license_url for GitHub Importer

vulnerabilities/api.py, vulnerabilities/tests/test_api.py
=> Fix severity range

requirements.txt, setup.cfg, vulnerabilities/improvers/valid_versions.py, vulnerabilities/tests/pipelines/test_github_importer_pipeline.py, vulnerabilities/tests/pipelines/test_nginx_importer_pipeline.py, vulntotal/datasources/github.py
Includes bug fix to fetchcode.package_versions.versions
=> Bump fetchcode from v0.3.0 to v0.6.0

vulnerabilities/pipelines/enhance_with_kev.py
- Resoves #1643
- Resolves #1532
=> Use AboutCode mirror for collecting CISA KEV

vulnerabilities/templates/index.html, vulnerabilities/views.py
| Bottom? | Top? | 
| ------------- | ------------- | 
| ![Screenshot from 2025-01-14 17-14-46](https://github.com/user-attachments/assets/33e1c7b1-05f4-484c-9c11-c5dfb4911f61) | ![Screenshot from 2025-01-14 17-18-33](https://github.com/user-attachments/assets/5b2f4986-caa9-4c99-83e3-de80b4a23a6c) |
- Resolves https://github.com/aboutcode-org/vulnerablecode/issues/1077
=> Add description and reference to the latest release on the homepage

vulnerabilities/templates/index.html
| ![Screenshot from 2025-03-26 21-26-04](https://github.com/user-attachments/assets/2d5bf1c2-7bd9-4896-861e-20b9bd8f4dad)  |
| ------------- |
=> Move the package search box to the top

vulnerabilities/importers/osv.py
Reference: https://github.com/aboutcode-org/vulnerablecode/issues/1851
=> Stop github OSV importer crashes
