- .travis.yml
- README.md
- vulnerablecode/dev.py
- vulnerablecode/settings.py
The changes were made on top of my branch for #47. So it makes sense to review/merge #52 first.
> Remove hard-coded SECRET_KEY from production settings

- README.md
- vulnerabilities/management/commands/import.py
- vulnerabilities/tests/test_import_cli.py
This change implements the custom management command "import" that allows
- listing all available data sources
- importing data from one or more sources by name (e.g. "debian")
- importing data from all sources
closes #54 
Signed-off-by: Haiko Schol <hs@haikoschol.com>
> Provide CLI for data import

- vulnerabilities/scraper/npm.py
Signed-off-by: sbs2001 <shivam.sandbhor@gmail.com>
Possibly fixes https://github.com/nexB/vulnerablecode/issues/126 
Also implements the following logic and prevents the behaviour given below.
> Unaffected version is that version which  is in the fixed_version_range or which is absent in the aff_version_range
Before patch:
```
>>> import npm
>>> z=npm.extract_versions('ldapauth',"<=2.2.4","<0.0.0")
>>> z
(['1.0.0', '1.0.1', '1.0.2', '2.0.0', '2.1.0', '2.2.0', '2.2.1', '2.2.2', '2.2.3', '2.2.4'], [])
```
After patch:
```
>>> import npm
>>> z=npm.extract_versions('ldapauth',"<=2.2.4","<0.0.0")
>>> z
(['1.0.0', '1.0.1', '1.0.2', '2.0.0', '2.1.0', '2.2.0', '2.2.1', '2.2.2', '2.2.3', '2.2.4'], ['2.3.0', '2.3.1'])
```
Here are some details regarding [ldapauth …
> Fix npm.py bug

- vulnerabilities/fixtures/debian.json
- vulnerabilities/fixtures/ubuntu.json
- vulnerabilities/tests/test_api.py
This change adds database fixtures for use in API tests to avoid running importer code as part of the test.
> Remove dependency on importers from API tests

- requirements.txt
- vulnerabilities/data_dump.py
- vulnerabilities/management/commands/import.py
- vulnerabilities/scraper/rust.py
This is the format of data obtained from  https://github.com/RustSec/advisory-db
`{'package_name': 'yaml-rust', 'vuln_id': 'RUSTSEC-2018-0006', 'fixed_versions': {'0.4.1', '0.4.3', '0.4.2'}, 'affected_versions': {'0.3.5', '0.3.0', '0.2.2', '0.2.1', '0.3.2', '0.3.3', '0.4.0', '0.2.0', '0.3.4'}, 'advisory': 'https://github.com/chyh1990/yaml-rust/pull/109'}`
Fixes https://github.com/nexB/vulnerablecode/issues/92
> Add rust security importer

- vulnerabilities/scraper/rust.py
This is a PR to solve this issue : https://github.com/nexB/vulnerablecode/issues/154
> fix: check for 'patched_versions' key

- vulnerabilities/data_dump.py
- vulnerabilities/management/commands/import.py
- vulnerabilities/scraper/safety_db.py
This data is imported from https://github.com/pyupio/safety-db .
> Add  importer for safetydb

- requirements.txt
- vulnerabilities/data_dump.py
- vulnerabilities/scraper/npm.py
- vulnerabilities/tests/test_npm.py
This fixes https://github.com/nexB/vulnerablecode/issues/162
Also made some changes to npm importer, like replacing semantic_version with dephell_specifier. The data_dump is modified such that now we are able to construct purls from the data obtained from the npm importer.
> Fix npm importer

- README.md
- pytest.ini
- vulnerabilities/data_dump.py
- vulnerabilities/tests/test_npm.py
- vulnerabilities/tests/test_rust.py
This is done by adding pytest markers on the tests which require internet connections , thus they can be skipped if necessary easily.
Simply run `DJANGO_DEV=1 pytest  -m "not webtest"`
> Allow skipping internet dependent tests, fix npm dump

- vulnerabilities/scraper/archlinux.py
- vulnerabilities/scraper/debian.py
Continuation of  https://github.com/nexB/vulnerablecode/pull/171 . 
This includes validators for debian, archlinux importers.
> Add schema validators for debian, archlinux importers

- .travis.yml
- README.md
- vulnerabilities/scraper/lib_oval.py
- vulnerabilities/scraper/oval_parser.py
- vulnerabilities/tests/test_data/ubuntu_oval_data.xml
- vulnerabilities/tests/test_ubuntu.py
TODOs : 
**How  is  this implemented ?**  
Oval files basically contain the following elements : OvalObjects, OvalStates , OvalTests, OvalDefinitions, OvalVariables . 
What the parser does, is take in  the OVAL document(xml file), get all the definitions. Then iterate over each definition, while doing so it does the following for every definition. 
0.Every definition has enclosed within a vulnerability id and the vulnerability description, we collect these.
1.Collect all the OvalTests which are referred to , within the OvalDefinition's body
2.This OvalTest has a OvalObject and OvalState nested within. 
3.From (2) go take the OvalObject, this has generally a OvalVariable nested within (or it may directly has a single package name enclosed within )
4.Iterate  over the children of the …
>  Add OVAL parser for Ubuntu

- vulnerabilities/scraper/lib_oval.py
- vulnerabilities/scraper/oval_parser.py
No need for `PerformantOvalDocument` in oval_parser.py as lib_oval.py is now improved(check https://github.com/CISecurity/OVALRepo/pull/1820).
> Update lib_oval.py and remove PerformantOvalDocument from oval_parser.py

- .travis.yml
- README.md
- vulnerabilities/scraper/oval_parser.py
- vulnerabilities/tests/test_data/suse_oval_data.xml
- vulnerabilities/tests/test_suse.py
- vulnerabilities/tests/test_ubuntu.py
Fortunately we hit the **Best Case scenario** in regards to OVAL parser. For context I first  made a OVAL parser for Ubuntu, then other for SUSE,  the plan was to have single OVAL parser for both, i.e to merge these into one. This is done by this PR
I also checked it with debian OVAL files, and those are working fine as expected .  
Competely fixes https://github.com/nexB/vulnerablecode/issues/145
Gets us very close to fix https://github.com/nexB/vulnerablecode/issues/59 , https://github.com/nexB/vulnerablecode/issues/62
> Generalise the UbuntuOvalParser to work with SUSE oval files

- vulnerabilities/management/commands/import.py
> Add CLI option to specify batch_size for the ImportRunner

- vulnerabilities/data_source.py
- vulnerabilities/import_runner.py
- vulnerabilities/importers/rust.py
- vulnerabilities/tests/test_import_runner.py
This will enable the us to update the config of an Importer after each run.  Essential to utilise Etags, and for https://github.com/nexB/vulnerablecode/pull/188
> Make the config of Importer  'updateable'

- vulnerabilities/importers/retiredotnet.py
- vulnerabilities/migrations/0010_retiredotnet_importer.py
- vulnerabilities/tests/test_data/retiredotnet/test_file.json
- vulnerabilities/tests/test_retiredotnet.py
Data is collected from https://github.com/RetireNet/Packages .
Fixes https://github.com/nexB/vulnerablecode/issues/197
> Add importer for RetireDotnet

- vulnerabilities/import_runner.py
- vulnerabilities/tests/test_import_runner.py
Bugfix: For advisories with a CVE ID that don't exist in the database yet, the summary was not stored.
> Store summary in `_insert_vulnerabilities_and_references()`

- vulnerabilities/importers/suse_backports.py
- vulnerabilities/migrations/0011_susebackports_importer.py
- vulnerabilities/tests/test_data/suse_backports/backports-sle11-sp0.yaml
- vulnerabilities/tests/test_suse_backports.py
This data is imported from http://ftp.suse.com/pub/projects/security/yaml/ , these are backports of previously vulnerable versions of packages, hence don't result into creation of `ImpactedPackages`. 
**Note**  : This data is different from SUSE OVAL files.
Gets close to  fix : https://github.com/nexB/vulnerablecode/issues/62  https://github.com/nexB/vulnerablecode/issues/84
> Add SUSE backport data source and it's tests

- vulnerabilities/migrations/0001_initial.py
I forgot to update this when switching to a newer release of packageurl-python, which has the limit set to 100.
Since there is no production deployment of the project yet, I changed the existing migration instead of adding a new one that modifies the column.
> Fix max_length for Package.version in initial migration

- vulnerabilities/data_source.py
- vulnerabilities/import_runner.py
- vulnerabilities/importers/debian_oval.py
- vulnerabilities/migrations/0012_debian_oval_importer.py
- vulnerabilities/oval_parser.py
- vulnerabilities/tests/test_data/debian_oval_data.xml
- vulnerabilities/tests/test_debian_oval.py
Fixes https://github.com/nexB/vulnerablecode/issues/198
Collects debian OVALs from https://www.debian.org/security/oval/
> Add Debian OVAL importer

- vulnerabilities/importers/redhat.py
- vulnerabilities/migrations/0013_redhat_importer.py
- vulnerabilities/tests/test_data/redhat.json
- vulnerabilities/tests/test_redhat_importer.py
Data is imported from  https://access.redhat.com/hydra/rest/securitydata/cve.json 
Fixes https://github.com/nexB/vulnerablecode/issues/44
Here is a glimpse of the data provided by this importer 
> Add red hat importer and it's tests

- vulnerabilities/data_source.py
This small change enables huge imports to run without consuming all the RAM
> Use yield to save memory in OvalDataSource's updated_advisories

- vulnerabilities/import_runner.py
Before this change, when a new vulnerability was stored for an advisory that has both a CVE ID and a summary, the summary was not included.
> Always store summary of vulnerability

- vulnerabilities/data_source.py
- vulnerabilities/import_runner.py
- vulnerabilities/importers/alpine_linux.py
- vulnerabilities/importers/archlinux.py
- vulnerabilities/importers/debian.py
- vulnerabilities/importers/gentoo.py
- vulnerabilities/importers/github.py
- vulnerabilities/importers/npm.py
- vulnerabilities/importers/openssl.py
- vulnerabilities/importers/redhat.py
- vulnerabilities/importers/retiredotnet.py
- vulnerabilities/importers/ruby.py
- vulnerabilities/importers/rust.py
- vulnerabilities/importers/safety_db.py
- vulnerabilities/importers/ubuntu_usn.py
- vulnerabilities/tests/test_archlinux.py
- vulnerabilities/tests/test_debian_oval.py
- vulnerabilities/tests/test_gentoo.py
- vulnerabilities/tests/test_github.py
- vulnerabilities/tests/test_import_runner.py
- vulnerabilities/tests/test_openssl.py
- vulnerabilities/tests/test_redhat_importer.py
- vulnerabilities/tests/test_retiredotnet.py
- vulnerabilities/tests/test_ruby.py
- vulnerabilities/tests/test_safety_db.py
- vulnerabilities/tests/test_suse_backports.py
- vulnerabilities/tests/test_ubuntu.py
- vulnerabilities/tests/test_ubuntu_usn.py
This is based on https://github.com/nexB/vulnerablecode/pull/219 so please review that before this. 
This PR is implementation of https://github.com/nexB/vulnerablecode/pull/216#issuecomment-653778007
Fixes https://github.com/nexB/vulnerablecode/issues/223
> Stick ref ids with urls

- vulnerabilities/importers/debian_oval.py
- vulnerabilities/importers/github.py
- vulnerabilities/importers/npm.py
- vulnerabilities/importers/ruby.py
- vulnerabilities/importers/rust.py
- vulnerabilities/importers/safety_db.py
- vulnerabilities/importers/ubuntu.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_debian_oval.py
- vulnerabilities/tests/test_github.py
- vulnerabilities/tests/test_npm.py
- vulnerabilities/tests/test_package_managers.py
- vulnerabilities/tests/test_ruby.py
- vulnerabilities/tests/test_rust.py
- vulnerabilities/tests/test_safety_db.py
- vulnerabilities/tests/test_ubuntu.py
This works by  creating coroutines for all API calls at once in bulk. This cuts the time waiting for server to respond before making another request.
> Use ayncio for making  API  calls to obtain package versions

- vulnerabilities/importers/debian.py
- vulnerabilities/tests/test_debian.py
Debian's json security tracker provides a last-modifed date. This PR checks when the data was last imported and compares it with last-modifed date and decides whether to continue or not.
> Check date before downloading data

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/openssl.py
- vulnerabilities/importers/safety_db.py
- vulnerabilities/tests/test_safety_db.py
This enables the importers to know whether they already have the latest data by checking the changes in  etags.
> Save  etags to importers wherever possible

- requirements.txt
- vulnerabilities/api.py
- vulnerabilities/fixtures/debian.json
- vulnerabilities/fixtures/ubuntu.json
- vulnerabilities/models.py
- vulnerabilities/templates/vulnerability.html
- vulnerabilities/tests/test_api.py
- vulnerablecode/settings.py
- vulnerablecode/urls.py
TODOs 
1. Update documentation. ~Add tests specific to checking new API additions~
~2. Deal with inputting  packageurls as query param.~
>  Redesign  the rest API

- README.md
- vulnerabilities/templates/base.html
We have swagger docs for API. The reference to this docs is added in the README as well as the web interface.
> :memo: Update README and web interface to include reference to API

- Dockerfile
- README.md
- docker-compose.yml
- vulnerablecode/settings.py
Fixes https://github.com/nexB/vulnerablecode/issues/229
> Dockerize vulnerablecode

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/nvd.py
- vulnerabilities/tests/test_data/nvd/nvd_test.json
- vulnerabilities/tests/test_nvd.py
This branch is based on https://github.com/nexB/vulnerablecode/pull/227. 
Finally an importer for NVD. 
Fixes https://github.com/nexB/vulnerablecode/issues/71
> Add NVD importer

- vulnerabilities/tests/test_nvd.py
The tests were failing randomly because the Reference urls were not sorted
> :rotating_light: Fix broken NVD tests

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/project_kb_msr2019.py
> Add importer for project KB MSR2019 dataset

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/apache_httpd.py
>  Add Apache HTTPD advisory importer

- vulnerabilities/data_source.py
- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/kaybee.py
> Add kaybee statement importer

- requirements.txt
- vulnerabilities/import_runner.py
- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/github.py
- vulnerabilities/importers/nginx.py
- vulnerabilities/models.py
- vulnerabilities/package_managers.py
> Use packageurl version 0.9.3 and Add nginx importer

- README.rst
Fixes #282 .
I have added FAQ section in doc with a question related to importing data while setting up.
> Added faq section

- requirements.txt
- vulnerabilities/helpers.py
- vulnerabilities/import_runner.py
- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/alpine_linux.py
- vulnerabilities/importers/apache_httpd.py
- vulnerabilities/importers/debian_oval.py
- vulnerabilities/importers/kaybee.py
- vulnerabilities/importers/nginx.py
- vulnerabilities/importers/npm.py
- vulnerabilities/importers/nvd.py
- vulnerabilities/importers/openssl.py
- vulnerabilities/importers/project_kb_msr2019.py
- vulnerabilities/importers/ruby.py
- vulnerabilities/importers/rust.py
- vulnerabilities/importers/safety_db.py
- vulnerabilities/importers/suse_backports.py
- vulnerabilities/importers/ubuntu.py
- vulnerabilities/importers/ubuntu_usn.py
- vulnerabilities/management/commands/import.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_helpers.py
- vulnerabilities/tests/test_rust.py
- vulnerabilities/tests/test_ubuntu.py
- vulnerabilities/views.py
* Move the implementation of the methods for handling etags and different
file  formats into a separate `helpers.py` module to prevent code duplication
* Fix bugs in the msr2019 importer.
> Cleanup codebase and fix minor bugs and other improvements

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/apache_tomcat.py
- vulnerabilities/tests/test_apache_tomcat.py
- vulnerabilities/tests/test_data/apache_tomcat/security-9.html
Addresses https://github.com/nexB/vulnerablecode/issues/106
Based on top of https://github.com/nexB/vulnerablecode/pull/278
> Import apache tomcat

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/github.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_github.py
* The github importer used to abandon a vulnerability if
the affected package had invalid name. This PR changes that
behaviour to instead  skip the package and import the vulnerability
* This commit also enables github importer to import vulnerabilities for python
and rubygems packages. This is crucial since we can't  use safetydb
> Improve GitHub importer

- vulnerabilities/importers/debian.py
- vulnerabilities/tests/test_data/debian.json
- vulnerabilities/tests/test_debian.py
Fixes https://github.com/nexB/vulnerablecode/issues/165
> Stop debian importer from collecting temp vulnerabilities 

- vulnerabilities/importers/nginx.py
- vulnerabilities/tests/test_data/nginx/security_advisories.html
- vulnerabilities/tests/test_data/postgresql/advisories.html
- vulnerabilities/tests/test_nginx.py
- vulnerabilities/tests/test_postgresql.py
Fixes https://github.com/nexB/vulnerablecode/issues/299
> Add tests for nginx and postgres importers

- requirements.txt
- vulnerabilities/templates/base.html
- vulnerablecode/settings.py
- vulnerablecode/urls.py
drf-yasg is not maintained and does not support OpenAPI 3.0.
> Use drf-spectacular instead of  drf-yasg for API docs

- vulnerabilities/api.py
- vulnerabilities/fixtures/debian.json
- vulnerabilities/tests/test_api.py
Fixes https://github.com/nexB/vulnerablecode/issues/284
> Add endpoints for bulk requesting vulnerabilities and packages

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/github.py
- vulnerabilities/tests/test_data/github_api/response.json
> Collect references from github  importer

- vulnerabilities/admin.py
- vulnerabilities/models.py
Fixes https://github.com/nexB/vulnerablecode/issues/315 
> Add django admin  functionality for searching and filtering objects

- vulnerabilities/forms.py
- vulnerabilities/templates/base.html
- vulnerabilities/templates/index.html
- vulnerabilities/templates/package_update.html
- vulnerabilities/templates/packages.html
- vulnerabilities/templates/vulnerabilities.html
- vulnerabilities/templates/vulnerability.html
- vulnerabilities/views.py
- vulnerablecode/settings.py
- vulnerablecode/urls.py
Fixes https://github.com/nexB/vulnerablecode/issues/324, https://github.com/nexB/vulnerablecode/issues/320
> Improve UI

- etc/nix/flake.nix
As described in the readme section "Keeping the Nix setup in sync", this PR updates the pypi index reference in order to accommodate for the recent updates of Python deps, mainly ``pygit2==1.5.0`` which got released 2021-01-23.
Currently, the github workflow fails but this seems to be unrelated to Nix (alpine import error)
> Update Nix deps to incorporate latest Python packages

- vulnerabilities/importers/redhat.py
This importer failed at times toward the end of the fetch step when
reaching (and trying repeatidly) to re-fetch the last page.
The fix consists in fetching larger batches at once (10K instead of 1k)
which measn fewer API calls and less risk to be throttled and properly
handling exceptions and HTTP response codes and breaking rather than
retrying. This also adds some minimal logging.
> Make RedHat CVE import more robust

- setup.cfg
- vulnerabilities/data_source.py
- vulnerabilities/helpers.py
- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/ubuntu.py
- vulnerabilities/lib_oval.py
- vulnerabilities/lib_oval.py.ABOUT
- vulnerabilities/lib_oval.py.LICENSE
- vulnerabilities/oval_parser.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_basics.py
- vulnerabilities/tests/test_debian_oval.py
- vulnerabilities/tests/test_suse.py
- vulnerabilities/tests/test_ubuntu.py
There are a few issues with the Ubuntu Oval importer that was stuck.
This resolves some of these issues:
- Do not fail when there is a version range that cannot be parsed as a RangeSpecifier(). 
- Improve error handling
- Add simple logging using print statements to help monitor import progress
- Also apply minor code formatting.
- I also added a code comment about the Etag handling which IMHO are more problematic than helpful at this stage, especially when there is a failure during import. See also #321
> Improve Ubuntu OVAL importer

- etc/nix/flake.lock
- etc/nix/flake.nix
Simple update of the pypi index.
With a working [Nix]() setup, all you have to do is running ``./etc/nix/get-latest-pypi-deps-db.sh`` and use its output to update ``/etc/nix/flake.nix``
> Update pypi deps db to 2021-03-06.

- vulnerabilities/api.py
- vulnerabilities/fixtures/github.json
- vulnerabilities/models.py
- vulnerabilities/tests/test_api.py
Fix https://github.com/nexB/vulnerablecode/issues/351
> Send severity data along with vulnerability

- vulnerabilities/importer_yielder.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/istio.py
- vulnerabilities/tests/test_data/istio/test_file.md
- vulnerabilities/tests/test_istio.py
Added importer and tests for istio
Also added test files in <code>test_data/istio</code>
Fixes #302
> Add istio importer and tests

- vulnerabilities/importers/nginx.py
- vulnerabilities/importers/postgresql.py
BeautifulSoup would generate warnings without an explicit parser which
shows up in the test results as well.
It is always better to look at clean test results than one filled with
unnecessary warnings.
> Explicity provide lxml parser to beautifulsoup

- .github/workflows/main.yml
- .travis.yml
- README.rst
- vulnerablecode/urls.py
The earlier location http://127.0.0.1:8000/api/docs was a 404. As the
urls.py suggests, the README now reflects http://127.0.0.1:8000/api/schema/swagger-ui/
After the first install, activating the venv is done prior to installing
pytest, thus the system default pytest is being called. It is either
required to reactive venv or run pytest via python -m.
> Correct API docs path and fix pytest invocation

- vulnerabilities/importers/redhat.py
Issue Fix: #384.
Added Sanity checks for RedHat import failing.
> Sanity Checks for redhat import response

- vulnerabilities/data_source.py
- vulnerabilities/importers/alpine_linux.py
- vulnerabilities/tests/test_import_runner.py
This makes sure that vulnerability id supplied in alpine_linux importer
is either a cve, vulcoid or empty so as to stand on the definition of
vulnerability id.
It could be possible to introduce a validator at the model level for the
same as well using these functions.
I would propose that we create a validators class where we would keep some custom validators which could be used inside the models to keep the database protected against invalid input. One such validator for `vulnerability id` would look like the following
```python
def vulnerability_id_validator(id: str):
if id != "" and not (DataSource.is_cve(id) or DataSource.is_vulcoid(id)):
raise ValidationError("{}: not a valid cve or volcoid".format(id))
```
> Make sure vulnerability id is_cve or is_vulcoid

- vulnerabilities/package_managers.py
Another patch to make the tool work behind proxies #403 
Fix #403
> enable aiohttp client to trust environement for proxy

- vulnerabilities/management/commands/import.py
If there is an operational error on one of the importer, it is better to still run the other importers
Signed-off-by: Pierre Tardy <pierre.tardy@renault.com>
> import: continue upon failure

- Dockerfile
- README.rst
- vulnerablecode/settings.py
This is my last few fixes for today. 
We can now call vulnerable code enterprise ready ;)
> Misc fixes for deploying vulnerablecode on a container platform

- README.rst
- vulnerablecode/settings.py
when deploying this outside of heroku, we get strange 400 errors, which turn out to be this variable that needs to be configured.
> enable configuration of allowed host

- vulnerabilities/helpers.py
- vulnerabilities/importers/redhat.py
- vulnerabilities/tests/test_redhat_importer.py
This fixes #398. 
This PR is mainly comprises of following two commits.
---
Introduced and used a helper function for retries on 5xx errors. This is
important and some servers like bugzilla.redhat.com return 502 Proxy Error
which was the cause of #398
A ticket has been raised in RedHat here https://redhat.service-now.com/help?id=rh_ticket&table=sc_req_item&sys_id=278239541b1ba010477e43fccd4bcb4a
Here is the response from bugzilla-owner@redhat.com
> Yes, just back off a bit and retry when this happens. It's been a long-term issue and we're working on a way to address it but it will still take time. There's also a time-out on individual queries - if you're hitting that sometimes on other requests then you'll need to optimise them or break them up into smaller ones
---
This is mentioned in …
> Fix redhat import failure

- vulnerabilities/severity_systems.py
This could be used where the scale of scoring system is unspecified and do not correspond to a numeric representation. This must be used as the last resort. 
Required in https://github.com/nexB/vulnerablecode/pull/397#discussion_r603774595 and https://github.com/nexB/vulnerablecode/pull/393#discussion_r603964317
> Add unspecified scoring system

- .github/workflows/upstream_test.yml
- .travis.yml
- vulnerabilities/tests/test_upstream.py
> Add tests to  check upstream data

- vulnerabilities/helpers.py
Added $ in is_cve helper
Earlier: r"CVE-\d+-\d+" 
Now: r"CVE-\d+-\d+$" 
This would avoid any invalid matches that were happening earlier
> Resolves #399: Rectify invalid id in msr2019

- README.rst
Added commands to run in case of running into a ModuleNotFoundError
Signed-off-by: Pushpit <pushpit07@gmail.com>
> Fixes #312 : Added solution for ModuleNotFoundError

- .github/workflows/test-import-using-nix.yml
- etc/nix/get-latest-pypi-deps-db.sh
This PR automatically fetches the latest [pypi-deps-db](https://github.com/DavHau/pypi-deps-db) before running the automated Nix tests (Github Action). This does *not* commit the changes. However, this should make the nix tests keep running (on Github) when the ``requirements.txt`` change and the obvious fix is to fetch a new version of pypi-deps-db.
> Fix nix Github workflow

- vulnerabilities/management/commands/create_cpe_to_purl_map.py
This script enables users to create cpe - purl mapping like https://github.com/sbs2001/purl2cpe . 
Usage:
To include all purls (patched+vulnerable) in the data, use:
```
python manage.py create_cpe_to_purl_map 
```
To include only patched purls, use:
```
python manage.py create_cpe_to_purl_map --patched_purls_only
```
Or, to include only vulnerable purls use:
```
python manage.py create_cpe_to_purl_map --vulnerable_purls_only
```
> Add a management command for creating cpe2purl mapping

- vulnerabilities/templates/package_update.html
- vulnerabilities/templates/packages.html
- vulnerabilities/templates/vulnerabilities.html
- vulnerabilities/views.py
The UI makes bazillions of queries while searching for stuff. 
This PR fixes it by optimizing the ORM calls.
> Reduce queries in UI

- requirements.txt
- vulnerabilities/helpers.py
- vulnerabilities/importers/alpine_linux.py
- vulnerabilities/importers/elixir_security.py
- vulnerabilities/importers/istio.py
- vulnerabilities/importers/suse_backports.py
- vulnerabilities/importers/suse_scores.py
- vulnerabilities/tests/test_alpine.py
- vulnerabilities/tests/test_istio.py
use saneyaml. reorder and refactor imports
Fixes: https://github.com/nexB/vulnerablecode/issues/440
> Dump yaml in favor of saneyaml

- .github/workflows/main.yml
Actions are majorly meant to perform tests on our codebase, yet they spend majority of their time on setting up the environment. 
Currently this only speeds up the pytest actions. We may also improve other ones after a discussion.
This PR comprises of two commits. The profiling of both commits were performed in https://github.com/Hritik14/vulnerablecode/pull/2 and https://github.com/Hritik14/vulnerablecode/pull/3
---
commit 135c95f7bd7eb7bccede20366b6cda750d6eb213 (HEAD -> actions)
Author: Hritik Vijay <hritikxx8@gmail.com>
Date:   Thu May 20 22:25:42 2021 +0530
Use cache for pip
Earlier Install Dependencies used to take 50-60s α
Now it takes ~10s including cache retrival time β
The total workflow time has reduced from ~1:40 to ~0:55
α: …
> Improve actions time

- vulnerabilities/import_runner.py
Fixes: #475 
Early profiling showed that a lot of time was being wasted during auto
commits undertaken by django. Wraping the importer in an atomic block
avoids lots of database commits and shows huge performance improvement.
Alpine: 202.7s -> 50.9s
Archlinux 2116.6s -> 107.8s
Gentoo 3176.3s -> 225.8s
Yielding an average of 93% reduction in time (14x faster)
Before using atomic blocks:
```python
---> restats_alpine <---
Fri Jun 11 20:06:11 2021    restats_default/restats_alpine
17843326 function calls (17320561 primitive calls) in 202.763 seconds
Ordered by: internal time
List reduced from 2779 to 5 due to restriction <5>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
4155  128.501    0.031  128.501    0.031 {method 'commit' of 'psycopg2.extensions.connection' …
```
> Improve import time

- vulnerabilities/helpers.py
- vulnerabilities/importers/istio.py
helper for istio and mozilla importers
The following two alternatives are also proposed:
```py
def split_markdown_front_matter(lines: str) -> Tuple[str, str]:
fmlines = []
mdlines = []
splitter = mdlines
for index, line in enumerate(lines.split("\n")):
if index == 0 and line.strip().startswith("---"):
splitter = fmlines
elif line.strip().startswith("---"):
splitter = mdlines
else:
splitter.append(line)
return "\n".join(fmlines), "\n".join(mdlines)
```
and the one present [here](https://github.com/mozilla/foundation-security-advisories/blob/d43d09d204ab5da014e83b7d1743df289cefee92/check_advisories.py#L183-L208) under MPL license.
> helper: split_markdown_front_matter

- vulnerabilities/importers/github.py
> Ignore legacy pypi package versions in github importer

- vulnerabilities/package_managers.py
Fixes: https://github.com/nexB/vulnerablecode/issues/492
Use uniform names and prototypes for `fetch` method.
Remove unnecessary checks. Re-use sessions.
I've removed `endpoint` argument from GitHubTagsAPI, I did not find a use for it at the current stage. Also, the `fetch` method is only called for the pkg which is not already in cache, so other checks appeared redundant. Please correct me if I am wrong.
---
Move load_api to parent class and refactor imports
The code for `load_api` was repetitive and used in all subclasses of
VersionAPI, it is better suited in the parent class. `fetch` method is
also now consistent and defined as an abstract method in the base class.
Python ABC is not used as different implementations of `load_api` and
`fetch` are allowed as done in DebianVersionAPI …
> Refactor package_managers

- vulnerabilities/data_source.py
- vulnerabilities/importers/nginx.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_debian_oval.py
- vulnerabilities/tests/test_ubuntu.py
Update importers to handle VersionResponse
======================================
Recent time travel heuristics need published date of versions, thus
Version dataclass was created. Some of the importers got bugged by this
new system and were crashing. This fix is a part of #467
Importers bugged:
- nginx
- debian_oval
- ubuntu
**NOTE**:  26e91f79e7c48e55e32faa4948af2f0cfdf28f94 should be reconsidered if https://github.com/nexB/vulnerablecode/issues/500 plans to revert #467
---
Fix recursion in GitHubTagsAPI
==========================
A minor bug was introduced by 775aa1d7 which was crashing the nginx
importer.
> Importers bugfix [nginx, debian_oval, ubuntu]

- README.rst
- docs/docker_installation.rst
This is a part of 1ab0b28
Totally my mistake to leave this file out.
> Add docker docs

- requirements.txt
- vulnerabilities/package_managers.py
Surprisingly, GitHub allows svn requests to repositories. Now we can
have all the tags with a single request. This is much more efficient and
gentle to the APIs.
@pombredanne thank you so much for the suggestion
> Use svn to collects tags in GitHubTagsAPI

- .github/workflows/upstream_test.yml
- Makefile
Refactor upstream tests to use makefile and standard installation
procedure. Also, it explicitly makes sure python version we test is
3.8.11
> Make upstream tests use makefile

- .github/workflows/main.yml
- README.rst
The badge now only sync with main branch and the main tests.
> Fix GitHub CI badge

- .github/workflows/docs.yml
- vulnerabilities/importers/debian.py
- vulnerabilities/tests/test_debian.py
Some tests were failing.
This is fixing this
> Ensure Debian test are passing

- README.rst
fixes #547 
Fixed the broken Docker Installation link in the README.rst file under the 'Setting up VulnerableCode' section
> Fixed the broken Docker Installation Link

- etc/nix/flake.nix
- etc/nix/test-import-using-nix.sh
This PR fixes several issues with the Nix setup. Note that the GitHub actions still doesn't run. I don't know what exactly the problem is but have reported it upstream (https://github.com/DavHau/mach-nix/issues/318).
Signed-off-by: Rolf Schröder <rolf.schr@gmail.com>
> Fix several problems with the nix setup.

- README.rst
- vulnerabilities/package_managers.py
the trust_env parameter is mandatory in ClientSession in order to support working behind a proxy
Fix: #556
> DebianVersionAPI: automatic support for proxy

- vulnerabilities/models.py
Issue:
The application can be started in it's current state because ugettext_lazy was deprecated. See https://forum.djangoproject.com/t/importerror-cannot-import-name-ugettext-lazy-from-django-utils-translation/10943
Fix:
Replaced deprecated API with supported one
This Fixes #587 (actually, only the use of an API deprecated in Django 4.x)
> Fix deprecated Django API

- .github/workflows/test-import-using-nix.yml
- etc/nix/flake.lock
- etc/nix/flake.nix
- etc/nix/lib.sh
- etc/nix/test-import-using-nix.sh
This PR addresses https://github.com/nexB/vulnerablecode/issues/617. I incorporated several changes that should make the Nix setup more compatible with the rest of the code base. Mainly, the `Makefile` is now used wherever possible. Fortunately, several env vars can be used to tweak the Makefile behavior (or better: the invoked commands).
> Fix nix setup

- vulnerabilities/helpers.py
- vulnerabilities/importers/github.py
- vulnerabilities/package_managers_2.py
- vulnerabilities/tests/test_data/package_manager_data/gem.json
- vulnerabilities/tests/test_helpers.py
- vulnerabilities/tests/test_package_managers_2.py
> Fix github improver

- vulnerabilities/tests/test_fix_api.py
> Add tests for checking the API

- vulnerabilities/import_runner.py
- vulnerabilities/improve_runner.py
This was a silent bug which got highlighted after writing tests for https://github.com/nexB/vulnerablecode/pull/672
> Fix improver framework not accepting severities

- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/test-import-using-nix.yml
This is to streamline CI runs:
- run import tests once a day on schedule
- run tests on all supported Pythons
> Improve test run

- vulnerabilities/importers/alpine_linux.py
- vulnerabilities/importers/nvd.py
- vulnerabilities/improver.py
- vulnerabilities/improvers/__init__.py
- vulnerabilities/improvers/default.py
- vulnerabilities/tests/test_data/default_improver/alpine-expected.json
- vulnerabilities/tests/test_data/default_improver/alpine-input.json
- vulnerabilities/tests/test_data/default_improver/nvd-expected.json
- vulnerabilities/tests/test_data/default_improver/nvd-input.json
- vulnerabilities/tests/test_default_improver.py
> Allow default improver to improve without affected packages

- vulnerabilities/improver.py
- vulnerabilities/improvers/default.py
- vulnerabilities/tests/test_default_improver.py
Also return an empty list instead of returning None when there is no advisory data passed in get_inferences
> Amend to_dict function for inferences

- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/redhat.py
- vulnerabilities/rpm_utils.py
- vulnerabilities/templates/vulnerability.html
- vulnerabilities/tests/conftest.py
- vulnerabilities/tests/test_data/redhat/RHSA-2022:1437.json
- vulnerabilities/tests/test_data/redhat/RHSA-2022:1439.json
- vulnerabilities/tests/test_data/redhat/bugzilla-2075788.json
- vulnerabilities/tests/test_data/redhat/bugzilla-2077736.json
- vulnerabilities/tests/test_data/redhat/redhat-expected.json
- vulnerabilities/tests/test_data/redhat/redhat-input.json
- vulnerabilities/tests/test_redhat_importer.py
> Migrate redhat importer

- requirements.txt
- setup.cfg
- vulnerabilities/helpers.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/pysec.py
- vulnerabilities/tests/test_data/pysec/pysec_test.json
- vulnerabilities/tests/test_pysec.py
#607 
Signed-off-by: Ziad <ziadhany2016@gmail.com>
> Add PyPI OSV

- requirements.txt
- vulnerabilities/helpers.py
- vulnerabilities/importer.py
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/debian.py
- vulnerabilities/importers/github.py
- vulnerabilities/improvers/__init__.py
- vulnerabilities/templates/vulnerabilities.html
- vulnerabilities/tests/conftest.py
- vulnerabilities/tests/test_data/debian-expected.json
- vulnerabilities/tests/test_data/debian-improver-expected.json
- vulnerabilities/tests/test_data/debian.json
- vulnerabilities/tests/test_debian.py
> Migrate debian importer to importer-improver model

- vulnerabilities/importers/github.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_data/github_api/composer-expected.json
- vulnerabilities/tests/test_data/github_api/composer.json
- vulnerabilities/tests/test_data/github_api/gem-expected.json
- vulnerabilities/tests/test_data/github_api/gem.json
- vulnerabilities/tests/test_data/github_api/golang-expected.json
- vulnerabilities/tests/test_data/github_api/golang.json
- vulnerabilities/tests/test_data/github_api/maven-expected.json
- vulnerabilities/tests/test_data/github_api/maven.json
- vulnerabilities/tests/test_data/github_api/nuget-expected.json
- vulnerabilities/tests/test_data/github_api/nuget.json
- vulnerabilities/tests/test_data/github_api/pypi-expected.json
- vulnerabilities/tests/test_data/github_api/pypi.json
- vulnerabilities/tests/test_utils.py
- vulnerabilities/utils.py
The GitHub importer failed to parse Composer packages who did not have a slash in their names. We now no longer raise an exception if a Composer package does not have "vendor/name" but only a plain name.
Also we were not getting the first patched version from the GitHub API using GraphQL. This PR is also fixing this.
Reference: https://github.com/nexb/vulnerablecode/issues/645
> Add firstPatchedVersion in github API

- vulnerabilities/importers/redhat.py
- vulnerabilities/tests/test_data/redhat/redhat-input.json
- vulnerabilities/tests/test_redhat_importer.py
> Put network calls in try/except block

- vulnerabilities/tests/test_view.py
- vulnerabilities/views.py
> Search from alias in UI

- CHANGELOG.rst
- vulnerablecode/static/api_doc/api_schema.yaml
> Add changelog

- CHANGELOG.rst
- vulnerabilities/api.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_fix_api.py
> Add fixed packages in packages endpoint

- CHANGELOG.rst
- vulnerabilities/api.py
- vulnerabilities/tests/test_fix_api.py
> Add namespace filter in packages api

- vulnerabilities/templates/base.html
- vulnerabilities/templates/navbar.html
- vulnerablecode/static/html/tos.html
Reference: https://github.com/nexB/vulnerablecode/issues/856
Reference: https://github.com/nexB/vulnerablecode/issues/923
Signed-off-by: John M. Horan <johnmhoran@gmail.com>
> Add TOS and API key contact info

- vulnerabilities/templates/navbar.html
Reference: https://github.com/nexB/vulnerablecode/issues/947
> Add API link/info to navbar

- CHANGELOG.rst
- setup.cfg
- vulnerablecode/__init__.py
This PR is to prepare a new minor release
> Prepare release 30.1.1

- vulnerabilities/importer.py
- vulnerabilities/importers/gitlab.py
- vulnerabilities/tests/conftest.py
- vulnerabilities/tests/test_data_source.py
Reference:  #806
Signed-off-by: ziad <ziadhany2016@gmail.com>
> Refactor Gitimporter using fetchcode

- docs/source/introduction.rst
Reference: https://github.com/nexB/vulnerablecode/issues/963
> Update RTD overview

- docs/source/introduction.rst
Reference: https://github.com/nexB/vulnerablecode/issues/963
> Add further updates to overview page

- CHANGELOG.rst
- vulnerabilities/api.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_fix_api.py
- vulnerabilities/tests/test_view.py
- vulnerabilities/views.py
> Ignore qualifiers and subpath from PURL search lookups #978

- CHANGELOG.rst
- vulnerabilities/tests/test_fix_api.py
- vulnerabilities/tests/test_throttling.py
- vulnerabilities/throttling.py
- vulnerablecode/settings.py
Enabled throttling for a basic user: 1000/day
And a staff user can have unlimited access on API
> Enable throttling

- CHANGELOG.rst
- vulnerabilities/forms.py
- vulnerabilities/templates/api_user_creation_form.html
- vulnerabilities/templates/navbar.html
> Fix the API key request form UI and make it consistent with rest of UI

- vulnerabilities/tests/test_data_migrations.py
* The code used to determine the name of the django app to perform test migrations on is a bit arcane
* By explicitly stating the app name, you can move the data migration test file to any location
Signed-off-by: Jono Yang <jyang@nexb.com>
> Explicitly state app name in TestMigration

- CHANGELOG.rst
- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/retiredotnet.py
- vulnerabilities/tests/conftest.py
- vulnerabilities/tests/test_data/retiredotnet/expected_file.json
- vulnerabilities/tests/test_retiredotnet.py
> Migrate retiredotnet importer

- .github/workflows/docs.yml
- SOURCES.rst
- docs/source/command-line-interface.rst
- docs/source/conf.py
- docs/source/contributing.rst
- docs/source/tutorial_add_new_importer.rst
Fixes: https://github.com/nexB/vulnerablecode/issues/1047
> Link sanity

- CHANGELOG.rst
- vulnerabilities/models.py
- vulnerabilities/tests/test_view.py
> Handle purl fragments in package search #1032

- CHANGELOG.rst
- requirements.txt
- setup.cfg
- vulnerabilities/importers/github.py
- vulnerabilities/package_managers.py
- vulnerabilities/tests/test_data/github_api/npm-expected.json
- vulnerabilities/tests/test_data/github_api/npm.json
- vulnerabilities/tests/test_github.py
> Ingest npm data through github api #1025

- CHANGELOG.rst
- vulnerabilities/models.py
- vulnerabilities/tests/test_view.py
- vulnerabilities/utils.py
> Support incomplete versions for a valid purl in search

- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/xen.py
- vulnerabilities/references.py
- vulnerabilities/tests/test_data/parse-advisory-xen-expected.json
- vulnerabilities/tests/test_data/xen_data.json
- vulnerabilities/tests/test_xen.py
> Migrate xen importer

- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/fireeye.py
- vulnerabilities/tests/test_data/fireeye/fireeye_test1.md
- vulnerabilities/tests/test_data/fireeye/fireeye_test1_expect.json
- vulnerabilities/tests/test_data/fireeye/fireeye_test2.md
- vulnerabilities/tests/test_data/fireeye/fireeye_test2_expect.json
- vulnerabilities/tests/test_fireeye.py
See https://github.com/nexB/vulnerablecode/issues/487
> Add fireeye vulnerabilities #487

- vulntotal/datasources/vulnerablecode.py
requires VCIO_TOKEN in .env file
Signed-off-by: Keshav Priyadarshi <git@keshav.space>
> use public VulnerableCode instance in VulnTotal 

- vulnerabilities/api.py
- vulnerabilities/tests/test_api.py
This is a first step towards #1090
> Add vulnerability aliases at package level in API

- CHANGELOG.rst
- vulnerabilities/importers/apache_httpd.py
- vulnerabilities/importers/apache_kafka.py
- vulnerabilities/tests/test_apache_kafka.py
> Fix Apache kafka and Apache httpd importer

- vulnerabilities/importer.py
- vulnerabilities/tests/test_affected_package.py
- vulnerabilities/tests/test_data/github_api/inference-expected.json
- vulnerabilities/tests/test_github.py
Affected version range does not support sort functionality, the merge function works fine if there is a single affected version range but fails for multiple affected version ranges.
> Fix affected package merge functionality

- vulnerabilities/import_runner.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_data/nginx/security_advisories-importer-expected.json
- vulnerabilities/tests/test_data/openssl/security_advisories-importer-expected.json
The NVD importer is failing to import due to this problem, since all other data is identical except weaknesses which is a new field on advisory, NVD importer is not able to create advisories.
> Add weakness in unique content ID in advisories

- CHANGELOG.rst
- vulnerabilities/models.py
- vulnerabilities/tests/test_models.py
- vulnerabilities/views.py
The problem with the CWE data is that there is no error handling when we try to access weakness using this ``weakness = self.db.get(self.cwe_id)``. For say CWE-189 which is a weakness associated with CVE-2009-3389 is not present in cwe2.database.
> Remove weaknesses from view which are not in DB

- vulnerabilities/improve_runner.py
- vulnerabilities/improver.py
- vulnerabilities/tests/test_improve_runner.py
- vulnerabilities/tests/test_improver.py
fixes: https://github.com/nexB/vulnerablecode/issues/612
> Add tests for improver

- vulnerabilities/templates/package_details.html
- vulnerablecode/static/css/custom.css
Reference: https://github.com/nexB/vulnerablecode/issues/1263
> Add sticky div to Package details template

- CHANGELOG.rst
- vulnerabilities/improve_runner.py
- vulnerabilities/improvers/valid_versions.py
We are having the same problem that we had with the default improver, the volume of advisories is too high and it eats up a lot of RAM, by paginating the advisories we will be able to save a lot of RAM.
> Add pagination to valid versions improver

- docs/source/installation.rst
With Django 4.0+ setting CSRF_TRUSTED_ORIGINS is necessary. Refer: https://stackoverflow.com/a/70326426/2251364
ScanCodeIO already recommends this setting in the following section: https://scancodeio.readthedocs.io/en/latest/installation.html#run-the-app
> Add note about CSRF_TRUSTED_ORIGINS

- .gitignore
- .readthedocs.yml
- apache-2.0.LICENSE
RTD builds were failing as we were not using the `build.os` field which is required.
This adds the RTD build conf from skeleton to fix the issue.
> Add RTD build configuration from skeleton

- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/oss_fuzz.py
- vulnerabilities/improvers/__init__.py
- vulnerabilities/improvers/valid_versions.py
- vulnerabilities/tests/test_data/oss_fuzz/oss-fuzz-data1.yaml
- vulnerabilities/tests/test_data/oss_fuzz/oss-fuzz-data1.yaml-expected.json
- vulnerabilities/tests/test_data/oss_fuzz/oss-fuzz-data2.yaml
- vulnerabilities/tests/test_data/oss_fuzz/oss-fuzz-data2.yaml-expected.json
- vulnerabilities/tests/test_oss_fuzz.py
using osv format #780 but we need to add support for oss-fuzz version , version range in univers and edit `get_fixed_version`
> Import data from OSS-Fuzz

- vulnerabilities/importers/github.py
- vulnerabilities/importers/gitlab.py
- vulnerabilities/importers/osv.py
- vulnerabilities/importers/redhat.py
- vulnerabilities/improvers/default.py
- vulnerabilities/tests/test_data/gitlab/composer-expected.json
- vulnerabilities/tests/test_data/gitlab/composer-improver-expected.json
- vulnerabilities/tests/test_data/gitlab/golang-expected.json
- vulnerabilities/tests/test_data/gitlab/golang-improver-expected.json
- vulnerabilities/tests/test_data/gitlab/maven-expected.json
- vulnerabilities/tests/test_data/gitlab/maven-improver-expected.json
- vulnerabilities/tests/test_data/gitlab/npm-expected.json
- vulnerabilities/tests/test_data/gitlab/npm-improver-expected.json
- vulnerabilities/tests/test_data/gitlab/nuget-expected.json
- vulnerabilities/tests/test_data/gitlab/nuget-improver-expected.json
- vulnerabilities/tests/test_data/gitlab/pypi-expected.json
- vulnerabilities/tests/test_data/gitlab/pypi-improver-expected.json
- vulnerabilities/tests/test_data/pysec/pysec-advisories_with_cwe-expected.json
- vulnerabilities/tests/test_data/pysec/pysec-advisory_with_cwe.json
- vulnerabilities/tests/test_data/redhat/redhat-expected.json
- vulnerabilities/tests/test_github.py
- vulnerabilities/tests/test_pysec.py
> Add CWE support in all importers

- vulnerabilities/api.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_api.py
> Add endpoint for purl lookup

- vulnerabilities/api.py
- vulnerabilities/tests/test_api.py
- Use `extend_schema` to override the request body, which was not being properly discovered.
- drf-spectacular relies on `get_serializer_class()` and `get_serializer()`, and it works well for view functions that purely deal with ModelSerializer. For anything else, it gets a bit murky, and it is advised to provide proper overrides in the `extend_schema` decorator.
- Override erroneous pagination and filter backend caused due to response containing multiple serializer object https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-action-is-erroneously-paginated-or-has-filter-parameters-that-i-do-not-want
> Fix swagger API docs generation

- vulnerabilities/api.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_api.py
- vulnerabilities/tests/test_data/suse_oval/suse-oval-CVE-2008-5679-expected.json
issue: #1094
Signed-off-by: ziadhany <ziadhany2016@gmail.com>
> Add CWE support in the API

- vulntotal/datasources/github.py
Fixes #1398 
Changes made : 
- Patched code in  datasource_advisory_from_cve function in GithubDataSource so that correct versions are displayed
> Fix incorrect versions in GithubDataSource CVE

- vulnerabilities/severity_systems.py
- vulnerabilities/templates/vulnerability_details.html
- vulnerabilities/templatetags/__init__.py
- vulnerabilities/templatetags/show_cvss.py
- vulnerabilities/tests/test_get_serverity.py
- vulnerabilities/views.py
This is an example of how to display CVSS vectors
#1239
> Add support for CVSS vectors display

- pyproject.toml
- vulntotal/datasources/__init__.py
- vulntotal/datasources/safetydb.py
- vulntotal/tests/test_data/safetydb/advisory.json
- vulntotal/tests/test_data/safetydb/parse_advisory-expected.json
- vulntotal/tests/test_data/safetydb/parse_advisory_cve-expected.json
- vulntotal/tests/test_safetydb.py
> Added safetydb datasource

- vulnerablecode/static/css/custom.css
Reference: https://github.com/nexB/vulnerablecode/issues/1299
> Increase display width #1299

- vulnerabilities/templates/rest_framework/api.html
Borrowed from ScanCode.io
Reference: https://github.com/nexB/vulnerablecode/issues/1465
Thanks-to: Thomas Druez @tdruez
> Add basic UI template for API

- vulnerabilities/templates/packages.html
Reference: https://github.com/nexB/vulnerablecode/issues/1501
Reference: https://github.com/nexB/vulnerablecode/issues/1520
@pombredanne @TG1999 -- ready for your review.
Note that when I ran `make test` locally, 1 test, unrelated to my update, failed:
```
FAILED vulnerabilities/tests/test_github_osv.py::GithubOSVImporter::test_github_osv_importer7 - TypeError: unhashable type: 'Version'
```
The updated column now looks like this:
> Rename "Fixed by vulnerabilities" column

- vulnerabilities/templates/packages.html
Reference: https://github.com/nexB/vulnerablecode/issues/1520
Related prior issue: https://github.com/nexB/vulnerablecode/issues/1501
Updates: https://github.com/nexB/vulnerablecode/pull/1519
@pombredanne  This supplements https://github.com/nexB/vulnerablecode/pull/1519, which did not yet include today's update.
The updated Package search response page:
> Finish renaming the former 'Fixed by vulnerabilities' column

- requirements.txt
- setup.cfg
- vulnerabilities/tests/test_data/apache_kafka/apache-kafka-improver-expected.json
- vulntotal/datasources/deps.py
- vulntotal/datasources/github.py
- vulntotal/datasources/gitlab.py
- vulntotal/datasources/snyk.py
- vulntotal/tests/test_data/github/parse_advisory-expected.json
- vulntotal/vulntotal_cli.py
- vulntotal/vulntotal_utils.py
- Add debug flag --vers to display equivalent normalized versions for corresponding native ranges.
- Add debug flag --no-compare to run the CLI without comparison.
- Dynamically adjust text table width based on the terminal width.
- Minor bug fixes and improvements in existing DataSources.
- Bump univers to v30.12.0
Depends on: https://github.com/nexB/univers/pull/108
Resolves #1136, resolves #822 
Note: Workflows is failing as https://github.com/nexB/univers/pull/108 is not yet merged in univers
> Support Advisory Comparison in VulnTotal

- vulnerabilities/management/commands/export.py
- vulnerabilities/tests/test_export.py
This PR exports VulnerableCode data in a file system structure suitable for use in FederatedCode.
> Export vulnerablecode-data

- vulnerabilities/importers/__init__.py
- vulnerabilities/importers/nvd.py
- vulnerabilities/importers/vulnrichment.py
- vulnerabilities/severity_systems.py
- vulnerabilities/templates/vulnerability_details.html
- vulnerabilities/tests/test_data/vulnrichment/vulnrichment-data1-expected.json
- vulnerabilities/tests/test_data/vulnrichment/vulnrichment-data1.json
- vulnerabilities/tests/test_data/vulnrichment/vulnrichment-data2-expected.json
- vulnerabilities/tests/test_data/vulnrichment/vulnrichment-data2.json
- vulnerabilities/tests/test_data/vulnrichment/vulnrichment-data3-expected.json
- vulnerabilities/tests/test_data/vulnrichment/vulnrichment-data3.json
- vulnerabilities/tests/test_vulnrichment.py
- vulnerabilities/views.py
> Add support to CVSSv4 & SSVC and import the data using vulnrichment

- vulnerabilities/models.py
- vulnerabilities/tests/test_models.py
We had a duplicated Package.get_non_vulnerable_versions method. This removes a dupe and merges the code of both functions. Package.get_non_vulnerable_versions now returns a Package object
> Remove dupe Package.get_non_vulnerable_versions

- .github/workflows/pypi-release.yml
- Use the same major version for upload-artifact and download-artifact
> Bump upload-artifact to v4

- CHANGELOG.rst
- vulnerabilities/management/commands/commit_export.py
- Resolves https://github.com/aboutcode-org/federatedcode/issues/20
> Add management command to commit exported data

- requirements.txt
- setup.cfg
- vulnerabilities/api.py
- vulnerablecode/settings.py
- Fixes https://github.com/aboutcode-org/vulnerablecode/issues/1602
| ![Screenshot from 2024-10-03 12-44-48](https://github.com/user-attachments/assets/e098dab0-b41f-4839-84ce-026db5af0bc3) | ![Screenshot from 2024-10-03 12-44-25](https://github.com/user-attachments/assets/661f9737-6c6e-4ae8-8d21-f6c5bafa2adc) |
| ------------- | ------------- |
|  ![Screenshot from 2024-10-03 12-44-14](https://github.com/user-attachments/assets/8e217cb1-46ba-4263-9447-267f169792cd) | ![Screenshot from 2024-10-03 12-43-55](https://github.com/user-attachments/assets/29de6ab9-cb4c-45d1-9ada-901fb75af74e)  |
> Fix 500 Server Error with DRF browsable API and resolve blank Swagger API documentation

- vulnerabilities/api.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_api.py
- vulnerablecode/settings.py
| ![Screenshot from 2024-10-25 22-25-00](https://github.com/user-attachments/assets/43ee83b5-898b-4d09-a621-dd826c2ff829) |
| ------------- |
- Fixes #1557
> Fix 500 error in /api/cpes endpoint

- docs/source/contributing.rst
- docs/source/tutorial_add_importer_pipeline.rst
- docs/source/tutorial_add_improver_pipeline.rst
- vulnerabilities/pipelines/__init__.py
- vulnerabilities/pipelines/gitlab_importer.py
- vulnerabilities/pipelines/npm_importer.py
- vulnerabilities/pipelines/pypa_importer.py
- vulnerabilities/tests/pipelines/test_base_pipeline.py
- Resolves https://github.com/aboutcode-org/vulnerablecode/issues/1639
> Add `on_failure` to handle cleanup during pipeline failure

- vulnerabilities/api.py
- vulnerabilities/tests/test_api.py
Add severity score to associated references in package endpoint.
| ![Screenshot from 2024-11-15 11-19-29](https://github.com/user-attachments/assets/82fc81d8-536b-4fa1-9347-e8129a17eaa8) |
| ------------- |
> Add reference score to package endpoint 

- vulnerabilities/api.py
- vulnerabilities/tests/test_api.py
> Add scores in bulk search V1 API

- vulnerabilities/api.py
- vulnerabilities/api_v2.py
- vulnerabilities/models.py
- vulnerabilities/tests/test_api.py
- vulnerabilities/views.py
| Before | After |
| ------------- | ------------- |
|  ![Screenshot from 2024-11-20 16-02-29](https://github.com/user-attachments/assets/2342c41f-e527-40d3-8469-23b6ca95c1c6) | ![Screenshot from 2024-11-20 16-02-57](https://github.com/user-attachments/assets/9e49f4fb-6ff2-4e7d-af8c-9718dd92ff03) |
| Before | After |
| ------------- | ------------- |
|  ![Screenshot from 2024-11-20 18-18-02](https://github.com/user-attachments/assets/b41225fa-56d0-47aa-8df9-942a0e4a8e9f) | ![Screenshot from 2024-11-20 18-18-29](https://github.com/user-attachments/assets/837cf0f5-7aa9-40fe-96f5-05d67da5a40a) |
| Before | After |
| ------------- | ------------- |
|  ![Screenshot from 2024-11-22 13-29-56](https://github.com/user-attachments/assets/c87f97b5-5eae-4d14-9616-aaf7ca38ab62) | ![Screenshot from …
> Do not report ghost package as a fix for vulnerability

- vulnerabilities/api_v2.py
- vulnerabilities/tests/test_api_v2.py
Reference: https://github.com/aboutcode-org/vulnerablecode/issues/1665
> Add fixed by package in V2 API

- vulnerabilities/import_runner.py
- vulnerabilities/importer.py
- vulnerabilities/improvers/vulnerability_status.py
- vulnerabilities/migrations/0089_migrate_advisory_aliases.py
- vulnerabilities/migrations/0090_migrate_advisory_aliases.py
- vulnerabilities/models.py
- vulnerabilities/pipelines/add_cvss31_to_CVEs.py
- vulnerabilities/pipes/advisory.py
- vulnerabilities/tests/pipelines/test_base_pipeline.py
- vulnerabilities/tests/pipelines/test_nginx_importer_pipeline.py
- vulnerabilities/tests/pipelines/test_remove_duplicate_advisories.py
- vulnerabilities/tests/pipes/test_advisory.py
- vulnerabilities/tests/test_add_cvsssv31.py
- vulnerabilities/tests/test_changelog.py
- vulnerabilities/tests/test_compute_content_id.py
- vulnerabilities/tests/test_data/nginx/security_advisories-importer-expected.json
- vulnerabilities/tests/test_data/openssl/security_advisories-importer-expected.json
- vulnerabilities/tests/test_data_migrations.py
- vulnerabilities/tests/test_example.py
- vulnerabilities/tests/test_import_runner.py
- vulnerabilities/tests/test_improve_runner.py
- vulnerabilities/tests/test_openssl.py
- vulnerabilities/tests/test_postgres_workaround.py
- vulnerabilities/tests/test_vulnerability_status_improver.py
- vulnerabilities/utils.py
- resolves https://github.com/aboutcode-org/vulnerablecode/issues/1777
> Migrate Advisory aliases field to M2M relationship

- docker-compose.yml
https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device
```
ERROR:  could not resize shared memory segment "/PostgreSQL.638321836" to 16777216 bytes: No space left on device
db_1                        | 2025-06-06 08:41:21.323 GMT [120] STATEMENT:  SELECT DISTINCT "vulnerabilities_packagev2"."id", "vulnerabilities_packagev2"."type", "vulnerabilities_packagev2"."namespace", "vulnerabilities_packagev2"."name", "vulnerabilities_packagev2"."version", "vulnerabilities_packagev2"."qualifiers", "vulnerabilities_packagev2"."subpath", "vulnerabilities_packagev2"."package_url", "vulnerabilities_packagev2"."plain_package_url", "vulnerabilities_packagev2"."is_ghost", "vulnerabilities_packagev2"."risk_score", …
```
> Increase docker shared memory size

- vulnerabilities/templates/vulnerability_package_details.html
This PR addresses issue #1843 by adding a navigational link on the `/vulnerabilities/<vulnerability_id>/packages` page, allowing users to return to the corresponding vulnerability details page.
- Edited `vulnerability_package_details.html` template.
- Added a "← Back to Vulnerability" button linking to `{% url 'vulnerability_details' vulnerability.vulnerability_id %}`.
This improves user navigation by allowing a smooth way from package details to the main vulnerability page.
---
Please let me know if any changes are required or if there's anything else I should work on to improve this PR. I'm happy to make updates based on your feedback.
> Add back navigation link to vulnerability details page
